console.log("=========step1===============================");
const arraySeasonalFruits = ["Banana","Orange","Apple","Mango","Water Melon"];
var charIndex = arraySeasonalFruits[0];
console.log(`First fruit is : ${charIndex}`);
// var str = arraySeasonalFruits.length;
// console.log(`${str}`);
var charIndex = arraySeasonalFruits.slice(arraySeasonalFruits.length-1);
console.log(`last fruit is : ${charIndex}`);
console.log("=======Add element papaya before the element banana========");
arraySeasonalFruits.unshift("papaya");
console.log(arraySeasonalFruits);
console.log("=======Remove Mango ===============");
arraySeasonalFruits.splice(4,1);
console.log(arraySeasonalFruits);
console.log("==========Insert an element pineapple at last position===============");
arraySeasonalFruits.push("Pineapple");           // Adding element last using push method
console.log(arraySeasonalFruits);
console.log("============Insert an element Dragon fruit before water melon==============");
arraySeasonalFruits.splice(5,0,"Dragon fruit");
console.log(arraySeasonalFruits);
console.log("===========Replace an element orange with kiwi=============");
arraySeasonalFruits.splice(2,1,"kiwi");
console.log(arraySeasonalFruits);
console.log("===========log the elements starting from index 1 to 4============");
const arrayFromIndex3 = arraySeasonalFruits.slice(1,4);
console.log(arrayFromIndex3);
console.log("============only select last 3 element=========");
const subArray = arraySeasonalFruits.slice(4);
console.log(subArray);